### ISSUE TITLE
Any idea where 3d models might live?

### ISSUE THREAD

**Issue by Velkas** [JokerDKha/SOS-FoMT-LZS#4]
I found this useful tool to extract game assets from the disc file. I got all the 2d textures I needed from it for what I'm working on but I was wondering if I could also find the 3d model files. So far, the only thing I can find are the textures (dds files) that I wanted and a bunch of other random files with .bum extension which I'm told are poser bump files. Not certain though.

Any hints here?

**Comment by IdaeroAce** [comment]
I'm pretty sure the models are those .bum files 
I have no idea how to open it though, But, you can use NinjaRipper. It can extract to models, but last time I tried it doesnt extract the textures. Then you can use the textures from this tool.

This .bum file is model file by Marvelous. It's also used on Senran kagura and To Love Ru game, both require different Noesis script and totally not working for different games o.o
https://forum.xentax.com/viewtopic.php?t=17608
https://forum.xentax.com/viewtopic.php?t=16034

**Comment by Velkas** [comment]
Thanks, I managed to successfully rip a model using NinjaRipper. A little more involved but the output is perfect including default T-Poses for character models and perfectly mapped textures. Appreciate the info!
